version: '3.7'

services:

  web:
    image: web:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4010:7000
    # networks:
    #   - db
    environment:
      - HOST_POSTGRES=postgres
    depends_on:
      - postgres
    deploy:
      replicas: 6
      update_config:
        parallelism: 3
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 0.5G
  
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=library
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    ports:
      - 5433:5432
    # networks:
    #   - db
  
  # portainer:
  #   image: portainer/portainer:latest
  #   container_name: portainer
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./portainer-data:/data

# networks:
#   db:

volumes:
  postgres-data: