version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4010:7000
    networks:
      - db
    environment:
      - HOST_POSTGRES=postgres
  
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=library
    volumes:
      - './postgres:/var/lib/postgresql/data'
      - ./model/database.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5433:5432
    networks:
      - db

networks:
  db: